# Generated by Django 3.0.5 on 2024-06-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240608_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
